Langkah:

Buat dataset sederhana (XOR).

Inisialisasi bobot dan bias.

Implementasikan forward pass.

Hitung error dan lakukan backpropagation.

Update bobot menggunakan gradient descent.

In [1]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.27723842437770996
Epoch 1000, Loss: 0.2502770005631618
Epoch 2000, Loss: 0.25007978715047663
Epoch 3000, Loss: 0.25002254817656383
Epoch 4000, Loss: 0.24996930153665045
Epoch 5000, Loss: 0.2498730849584184
Epoch 6000, Loss: 0.24959186271757164
Epoch 7000, Loss: 0.24813510683382617
Epoch 8000, Loss: 0.23373802674485133
Epoch 9000, Loss: 0.1683124655279587
Prediksi:
[[0.21132439]
 [0.79289788]
 [0.8469402 ]
 [0.1801556 ]]


Tugas 1:

Ubah jumlah neuron hidden layer menjadi 3.

Bandingkan hasil loss dengan konfigurasi awal.

Tambahkan fungsi aktivasi ReLU dan bandingkan hasil.

In [3]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3   # 🔥 diubah dari 2 → 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Error
    error = y - a2

    # Backprop
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    # Print loss
    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

print("\nPrediksi akhir:")
print(a2)


Epoch 0, Loss: 0.31807557623044835
Epoch 1000, Loss: 0.20103778142322887
Epoch 2000, Loss: 0.12973985034723712
Epoch 3000, Loss: 0.05157437093170941
Epoch 4000, Loss: 0.02048592768307086
Epoch 5000, Loss: 0.010668141601886337
Epoch 6000, Loss: 0.006746480825421281
Epoch 7000, Loss: 0.004789175729075827
Epoch 8000, Loss: 0.0036555730363492306
Epoch 9000, Loss: 0.002929634311630131

Prediksi akhir:
[[0.03832821]
 [0.93592365]
 [0.96477056]
 [0.05392452]]


In [4]:
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)


In [5]:
import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

input_size = 2
hidden_size = 3
lr = 0.1

W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, 1)
b2 = np.zeros((1, 1))

# Aktivasi
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

for epoch in range(10000):
    # Forward
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)                # 🔥 ReLU di hidden layer
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)             # output tetap sigmoid

    # Error
    error = y - a2

    # Backprop
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1)   # 🔥 turunan ReLU
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

print("\nPrediksi akhir:")
print(a2)


Epoch 0, Loss: 0.29955525492941115
Epoch 1000, Loss: 0.0062378534094149445
Epoch 2000, Loss: 0.0019223759924373307
Epoch 3000, Loss: 0.0010864722954881687
Epoch 4000, Loss: 0.0007460558529050572
Epoch 5000, Loss: 0.0005642487625023654
Epoch 6000, Loss: 0.0004515580089440187
Epoch 7000, Loss: 0.0003755714186662561
Epoch 8000, Loss: 0.00032075039399604615
Epoch 9000, Loss: 0.0002795719911630705

Prediksi akhir:
[[0.01988244]
 [0.98995373]
 [0.99005687]
 [0.01988136]]
